# Generated by Django 3.0.1 on 2020-03-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0004_diseaseimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiseaseDetails',
        ),
    ]
