# Generated by Django 3.0.1 on 2020-03-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0005_delete_diseasedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cause', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('solution', models.CharField(max_length=1000)),
            ],
        ),
    ]
